name: 'latest'

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy-nacc-latest:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    env:
      BUILD_DIR: build
      ZIP_FILENAME_JS: naccjs.zip
      ZIP_FILENAME: nacc-wordpress-plugin.zip
      S3_KEY_JS: naccjs
      S3_KEY: nacc-wordpress-plugin
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v6

      - name: Setup Node.js 📦
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Build nacc2 JavaScript 🔨
        working-directory: nacc2
        run: |
          npm ci
          npm run build

      - name: Build nacc zip file 🔧
        run: make build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/gh-ci-s3-artifact
          role-session-name: gh-actions-nacc
          aws-region: us-east-1

      - name: copy nacc artifacts to s3 🪣
        run: |
          aws s3 cp $BUILD_DIR/$ZIP_FILENAME_JS s3://${{ secrets.S3_BUCKET }}/$S3_KEY_JS/naccjs-${{ github.run_number }}-${{ github.sha }}.zip
          aws s3 cp $BUILD_DIR/$ZIP_FILENAME s3://${{ secrets.S3_BUCKET }}/$S3_KEY/nacc-wordpress-plugin-${{ github.run_number }}-${{ github.sha }}.zip

      - name: Publish Release to Latest WP 🎉
        id: publish_latest
        uses: bmlt-enabled/wordpress-releases-github-action@v2
        with:
          file: ${{ env.BUILD_DIR }}/${{ env.ZIP_FILENAME }}
          aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          s3_key: ${{ env.S3_KEY }}
