name: 'pull-request'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v6
        id: code-checkout

      - name: Setup Node.js 📦
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Build nacc2 JavaScript 🔨
        working-directory: nacc2
        run: |
          npm ci
          npm run build

      - name: Validate composer.json and composer.lock 🎼
        id: composer-validate
        run: composer validate

      - name: PHPCS checker 🧹
        id: php-codesniffer
        run: make lint
