name: 'release'

on:
  push:
    tags: ['*']

jobs:
  deploy-nacc-release:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: write
    env:
      BUILD_DIR: build
      ZIP_FILENAME_JS: naccjs.zip
      ZIP_FILENAME: nacc-wordpress-plugin.zip
    steps:
      - name: Check out code 🛒
        uses: actions/checkout@v6

      - name: Setup Node.js 📦
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Build nacc2 JavaScript 🔨
        working-directory: nacc2
        run: |
          npm ci
          npm run build

      - name: Build nacc zip file 🔧
        run: make build

      - name: Generate Release Notes 📝
        if: github.ref_type == 'tag'
        run: |
          curl -LO https://raw.githubusercontent.com/bmlt-enabled/release-notes-tool/main/gh-release-notes.sh
          chmod +x gh-release-notes.sh
          ./gh-release-notes.sh readme.txt "wp"
          RELEASE_TYPE=$(if [[ "$GITHUB_REF_NAME" =~ "beta" ]]; then echo "true"; else echo "false"; fi)
          echo "RELEASE_TYPE=${RELEASE_TYPE}" >> $GITHUB_ENV

      - name: Create Release 🎉
        uses: ncipollo/release-action@v1
        if: github.ref_type == 'tag'
        with:
          artifacts: build/${{ env.ZIP_FILENAME }},build/${{ env.ZIP_FILENAME_JS }}
          bodyFile: "changelog.txt"
          prerelease: ${{ env.RELEASE_TYPE }}

      - name: Wordpress Release ⛴
        if: "!contains(github.ref, 'beta')"
        id: wordpress-stable-release
        env:
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          DIST_DIR_GITHUB: ${{ env.BUILD_DIR }}
          GITHUB_RELEASE_FILENAME: ${{ env.ZIP_FILENAME }}
          PLUGIN: nacc-wordpress-plugin
          MAINFILE: nacc-wordpress-plugin.php
        run: |
          curl -LO https://raw.githubusercontent.com/bmlt-enabled/bmlt-wordpress-deploy/master/deploy-wordpress.sh
          chmod +x deploy-wordpress.sh
          ./deploy-wordpress.sh
